# Practice on NumPy and pandas

Here are some task for you, to refresh what you saw in the notebooks before.

It will help you strengthen the **learning objectives** from the notebook before. You should be able to
- create NumPy arrays
- manipulate them with basic mathematics operators
- extract rows, columns and items by indexing
- use aggregation methods (like sum, min, max, std) on NumPy arrays


## Part 1: Creating NumPy arrays.

1. Please create a NumPy array from the list:
```Python
my_list = [1, 2, 5, 6, 8]
````

In [27]:
import numpy as np

my_list = np.array([1,2,5,6,8])
my_list

array([1, 2, 5, 6, 8])

2. Please create a NumPy array containing the values from 1 to 10.


In [28]:
my_list = np.array(range(1,11,1))
my_list

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

3. Please create a NumPy array from 0 to 5 with a step size of 0.2


In [29]:
my_list = np.arange(0,5.2,0.2)
my_list

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ])

4. Create a NumPy array with the shape 2,3 with random values


In [30]:
my_list = np.random.rand(2,3)
my_list

array([[0.38657778, 0.07074579, 0.34311913],
       [0.4844422 , 0.14905967, 0.57143119]])

## Part 2: Manipulate NumPy arrays.

1. Please create a NumPy array with (1, 3, '4', 7, 12, '0'). Define the content as integer.


In [31]:
my_list = np.array([1 ,3,"4",7,12,"0"], np.int32)
my_list

array([ 1,  3,  4,  7, 12,  0], dtype=int32)

2. Check the data type of the objects and the shape of the array


In [32]:
my_list.dtype

dtype('int32')

In [33]:
my_list.shape

(6,)

3. Update the 4th value to 30.


In [34]:
my_list[3] = 30

my_list

array([ 1,  3,  4, 30, 12,  0], dtype=int32)

4. Reshape the array to a 2x3 matrix.


In [35]:
my_list = my_list.reshape(2,3)
my_list

array([[ 1,  3,  4],
       [30, 12,  0]], dtype=int32)

5. Please add 8 to each value in the first row and 12 to each in the second row.


In [36]:
my_list = my_list + [[8],[12]]
my_list

array([[ 9, 11, 12],
       [42, 24, 12]])

6. Multiply the first column with 2, the second with 3 and the third with 4.


In [37]:
my_list = my_list * [2,3,4]
my_list

array([[18, 33, 48],
       [84, 72, 48]])

7. Please sum up all numbers in the first row, and all numbers in the second row.


In [38]:
my_list.sum(axis=1)

array([ 99, 204])

8. Similarly, search for the largest number for each column.


In [39]:
my_list.max(axis=0)

array([84, 72, 48])

9. Extract the number in the second column and the first row.


In [40]:
my_list[0, 1]

33

10. Check at which index the value is exactly 48.

In [41]:
np.where(my_list == 48)

(array([0, 1]), array([2, 2]))